# Generated by Django 4.0.3 on 2022-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Rooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Wifi', models.BooleanField()),
                ('Equipped', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Pool', models.BooleanField()),
            ],
        ),
    ]
