# Generated by Django 4.0.3 on 2022-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0002_rename_pool_product_gym_rename_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Rooms',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
