# Generated by Django 4.0.3 on 2022-03-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0003_product_phone_alter_product_rooms_alter_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Gym',
            new_name='pool',
        ),
    ]
