# Generated by Django 4.0.3 on 2022-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0004_rename_gym_product_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
