# Generated by Django 4.0.3 on 2022-03-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0007_alter_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
    ]
