# Generated by Django 4.0.3 on 2022-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0009_alter_product_options_product_last_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('Birthdate', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='Created',
        ),
    ]
