# Generated by Django 4.0.3 on 2022-04-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0010_userdata_rename_last_update_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Userdata',
            field=models.ManyToManyField(related_name='products', to='mem.userdata'),
        ),
    ]
