# Generated by Django 4.0.3 on 2022-04-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0011_product_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Userdata',
        ),
        migrations.AlterField(
            model_name='product',
            name='Equipped',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wifi',
            field=models.BooleanField(null=True),
        ),
    ]
