# Generated by Django 4.0.3 on 2022-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0012_remove_product_userdata_alter_product_equipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rooms',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
