# Generated by Django 4.0.3 on 2022-04-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0014_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title',
            new_name='name',
        ),
    ]
