# Generated by Django 4.0.3 on 2022-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0015_rename_title_reviews_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
